---
title: "Frequently Asked Questions"
output: html_document
---

-----

[Should I webscrape?](#should-i-webscrape)  
[What should I do after I webscrape?](#what-should-i-do-after-i-webscrape)  
[Why are websites unstable?](#why-are-websites-unstable)  
[How do I tell the computer what information I want?](#how-do-i-tell-the-computer-what-information-i-want)  
[What tools should I use?](#what-tools-should-i-use)  

-----

## Should I webscrape?

If there is information from a website that you need *and* the website allows webscraping, go for it!


## What should I do after I webscrape?

Save your intermediate results! You want to webscrape as few times as possible. And, if you save the information, you have what you need and won't be affected if the website changes in the future.


## Why are websites unstable?

Things change! Information gets aded and removed from websites all the time and they're completely redesigned regularly - that's how they stay up to date. Remember, the website exists to share information. It was not designed for you to get data easily. People are allowed to update their websites!

## How do I tell the computer what information I want?

Often in webscraping, we're exploiting the underlying HTML code, which utilizes specific tags for different parts of the website. Getting more familiar with HTML and HTML tags is a great way to understand more about web scraping!


## What tools should I use?

If you're using R, `rvest` is a great place to start!